using System;
using System.Collections.Generic;

namespace ProjectEuler
{
    public class Problem2
    {
        public static void DoIt()
        {
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");

            var sum            = 0;
            var evenValuedFibs = new List<int>();
            evenValuedFibs.Add(2);

            var fib = new List<int>();
            fib.Add(1);
            fib.Add(2);

            for (int i = 2; i < 100; i++)
            {
                var x = fib[i - 1] + fib[i - 2];
                Console.WriteLine($"{i:0000} {x}");
                if (x > 4000000)
                {
                    break;
                }

                fib.Add(x);
                if (x % 2 == 0)
                {
                    evenValuedFibs.Add(x);
                }
            }

            foreach (var evenValuedFib in evenValuedFibs)
            {
                Console.WriteLine(evenValuedFib);
                sum += evenValuedFib;
            }

            Console.WriteLine(sum);
        }
    }
}